### PR TITLE
Fix S3 media preview on library page of Wordpress Admin

### LINKED ISSUE #23: S3_UPLOADS_ENDPOINT env var is doesn't take into account
The endpoint that is the target is the AWS endpoint, even when this environment variable is used.
It is therefore not possible to use another S3 provider at the moment, only AWS works.

Upload to the right bucket is working perfectly.
But when we try to display the media on the library page of the Wordpress administration, the image is not displayed because it's not the right URL that is used.

### PR DESCRIPTION
**Pull request by brandon-welsch**
Fix #23 

Related to an issue from a customer

## Changelog
- Fix the preview of medias on library page of Wordpress Admin, related to s3 plugin configuration. See: https://github.com/humanmade/S3-Uploads/tree/3.0.3#url-rewrites
- Update `humanmade/s3-uploads` Wordpress plugin to 3.0.3
- Allow to customize `S3_UPLOADS_BUCKET_URL` from environment variable
- Use `getenv` (PHP builtin) instead of `env`

The documentation will be made in #22

### CODE REVIEW

File: config/environments/production.php [hunk 1]
```diff
@@ -11,6 +11,17 @@
 define('S3_UPLOADS_SECRET', env('S3_UPLOADS_SECRET'));
 define('S3_UPLOADS_REGION', env('S3_UPLOADS_REGION'));
 define('S3_UPLOADS_ENDPOINT', env('S3_UPLOADS_ENDPOINT'));
+define('S3_UPLOADS_BUCKET_URL', env('S3_UPLOADS_BUCKET_URL'));
+
+if (env('S3_UPLOADS_ENDPOINT') && env('S3_UPLOADS_BUCKET_URL') == '') {
```
Comment (EtienneM) [inline config/environments/production.php]: What if both `S3_UPLOADS_ENDPOINT` and `S3_UPLOADS_BUCKET_URL` are defined?

I actually find it really odd to have that many different environment variables to name the same thing. Isn't it possible to simplify?

File: config/environments/production.php [hunk 2]
```diff
@@ -11,6 +11,17 @@
...
+    $s3_endpoint = env('S3_UPLOADS_ENDPOINT');
+    $s3_bucket_name = env('S3_UPLOADS_BUCKET');
```
Comment (EtienneM) [inline config/environments/production.php]: nitpick: why don't you make the variable name the same as the environment variable name? 🤔 
```suggestion
    $s3_uploads_endpoint = env('S3_UPLOADS_ENDPOINT');
    $s3_uploads_bucket = env('S3_UPLOADS_BUCKET');
```

Comment (EtienneM) [reply config/environments/production.php]: `S3_UPLOADS_BUCKET` might be undefined in this condition

File: config/environments/production.php (hunk 1 above)
Comment (brandon-welsch) [reply config/environments/production.php]: If both are defined, it's good. The customer has the choice to define `S3_UPLOADS_BUCKET_URL` or not. If it is not defined (by default), we build ourselves the complete bucket URL with the required information. 

I don't think it can be simplified any further here. It's the way the plugin works. It's better to build on that than to change everything knowing that there is documentation on this plugin here: https://github.com/humanmade/S3-Uploads

File: config/environments/production.php [hunk 3]
```diff
@@ -6,11 +6,22 @@
 /** Disable all file modifications including updates and update notifications */
 define('DISALLOW_FILE_MODS', true);
 
-define('S3_UPLOADS_BUCKET', env('S3_UPLOADS_BUCKET'));
-define('S3_UPLOADS_KEY', env('S3_UPLOADS_KEY'));
-define('S3_UPLOADS_SECRET', env('S3_UPLOADS_SECRET'));
-define('S3_UPLOADS_REGION', env('S3_UPLOADS_REGION'));
-define('S3_UPLOADS_ENDPOINT', env('S3_UPLOADS_ENDPOINT'));
+define('S3_UPLOADS_BUCKET', getenv('S3_UPLOADS_BUCKET'));
```
Comment (EtienneM) [inline config/environments/production.php:9]: out of curiosity: what is the difference between `env` and `getenv`?

File: config/environments/production.php [hunk 4]
```diff
@@ -6,11 +6,22 @@
...
+define('S3_UPLOADS_ENDPOINT', getenv('S3_UPLOADS_ENDPOINT'));
+if (getenv('S3_UPLOADS_ENDPOINT') && getenv('S3_UPLOADS_BUCKET') && !getenv('S3_UPLOADS_BUCKET_URL')) {
+    $s3_uploads_endpoint = getenv('S3_UPLOADS_ENDPOINT');
+    $s3_uploads_bucket = getenv('S3_UPLOADS_BUCKET');
+    $parts = parse_url($s3_uploads_endpoint);
+    $bucket_url = $parts['scheme'] . "://" . $s3_uploads_bucket . "." . $parts['host'];
+
+    // Define the base bucket URL (without trailing slash)
+    define('S3_UPLOADS_BUCKET_URL', $bucket_url);
+} else {
```
Comment (EtienneM) [inline config/environments/production.php:22]: Don't you want to display a warning in case `S3_UPLOADS_BUCKET_URL`, `S3_UPLOADS_BUCKET` and `S3_UPLOADS_ENDPOINT` are defined? I mean, if someone defines a bucket in `S3_UPLOADS_BUCKET` and also defines `S3_UPLOADS_BUCKET_URL`, the bucket will completely be ignored. Isn't it confusing?

File: config/environments/production.php (hunk 3 above)
Comment (brandon-welsch) [reply config/environments/production.php:9]: `env` is a function from Wordpress. `getenv` is a function provided by PHP langage (builtin). I've seen a lot of people using it on the internet on the `wp-config.php` file with `define()`.

I used it because it's easier to know what exactly the documented PHP function does. Whereas the Wordpress one doesn't seem to be documented. I didn't find much.

File: config/environments/production.php (hunk 4 above)
Comment (brandon-welsch) [reply config/environments/production.php:22]: The `S3_UPLOADS_BUCKET` will probably be used by the plugin. S3_UPLOADS_BUCKET_URL is already defined in the plugin to `https://BUCKET_NAME.s3.amazonaws.com` => https://github.com/humanmade/S3-Uploads/blob/d3681c3b35cd4da439efdf62ed70898dbab7cb3c/inc/class-plugin.php#L227

There is no problem in using all the variables together.

Comment (brandon-welsch) [reply config/environments/production.php:22]: The env var `S3_UPLOADS_BUCKET_URL` is only there if the default system does not work. It will not be required and used by default. It's an optional env var.

Comment (EtienneM) [reply config/environments/production.php:22]: I'm sorry, I want to accept this PR but I don't understand what you say. I mean, what you say is that if the environment variable `S3_UPLOADS_BUCKET` is defined, the environment variable `S3_UPLOADS_BUCKET_URL` is ignored. Then there is something that is definitely confusing as I said. Did I miss something?

We can talk about it on Discord if you prefer

**Review by EtienneM — COMMENTED** [review]
I'm sorry, there is still something I don't understand

File: config/environments/production.php (hunk 4 above)
Comment (brandon-welsch) [reply config/environments/production.php:22]: The variable `S3_UPLOADS_BUCKET_URL` is ignored by default. And the default value of this setting is defined in the plugin if `S3_UPLOADS_ENDPOINT` is don't set. If the customer has a specific use, for example he would like to use `https://bucket.s3.fr-par.scw.cloud/directory/subdirectory` instead of `https://bucket.s3.fr-par.scw.cloud` (the default one used when `S3_UPLOADS_ENDPOINT` is defined to `s3.fr-par.scw.cloud` and `S3_UPLOADS_BUCKET` to `bucket`) it can use its configuration by specifying this environment variable.

This allows all types of bucket configuration to be accepted without changing the entire functionality.
If I haven't made it sufficiently clear, we can discuss this directly in the office.

**Review by EtienneM — APPROVED** [review]
